// Generated by tools/cut_heart_layers.py — do not edit by hand.
// Coordinates are base-image pixels, origin at the base's top-left.
import type { HeartLayerGeometry } from './heartLayers'

export const BASE_W = 608
export const BASE_H = 756

export const GEOMETRY: Record<string, HeartLayerGeometry> = {
  "RA": {
    "x": 73,
    "y": 289,
    "w": 167,
    "h": 240,
    "px": 153.7,
    "py": 409.5
  },
  "RV": {
    "x": 227,
    "y": 530,
    "w": 206,
    "h": 172,
    "px": 329.6,
    "py": 624.5
  },
  "PA": {
    "x": 263,
    "y": 158,
    "w": 265,
    "h": 178,
    "px": 341.0,
    "py": 329.0,
    "path": [
      [
        341.8,
        304.2
      ],
      [
        339.5,
        282.0
      ],
      [
        334.5,
        262.3
      ],
      [
        333.2,
        242.2
      ],
      [
        351.9,
        222.5
      ],
      [
        386.7,
        211.2
      ],
      [
        416.1,
        205.6
      ],
      [
        439.7,
        200.9
      ],
      [
        464.2,
        197.0
      ],
      [
        486.3,
        190.7
      ],
      [
        504.6,
        180.4
      ]
    ]
  },
  "LA": {
    "x": 339,
    "y": 258,
    "w": 173,
    "h": 184,
    "px": 427.7,
    "py": 336.1
  },
  "LV": {
    "x": 332,
    "y": 440,
    "w": 209,
    "h": 231,
    "px": 458.1,
    "py": 554.6
  },
  "AO": {
    "x": 183,
    "y": -1,
    "w": 265,
    "h": 358,
    "px": 242.0,
    "py": 350.0,
    "path": [
      [
        238.5,
        317.8
      ],
      [
        237.9,
        283.7
      ],
      [
        237.4,
        248.3
      ],
      [
        237.3,
        210.5
      ],
      [
        246.9,
        172.7
      ],
      [
        268.6,
        140.0
      ],
      [
        299.6,
        124.9
      ],
      [
        337.8,
        123.4
      ],
      [
        368.0,
        112.2
      ],
      [
        381.9,
        84.6
      ],
      [
        382.8,
        44.4
      ]
    ]
  }
} as const
